### ISSUE TITLE
Don't error out when staking if no Stake event occurs

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#160]
We will let users Stake a pre boosted proposal, and if that proposal is ready to boost and over the confidence threshold then the stake transaction will boost the proposal and not actually do the stake so no Stake event will be fired and we get an error Error staking: no "Stake" event was found. Let's eliminate that error since there is no actual problem here

**Comment by jellegerbrandy** [comment]
Your observations are right, but I have doubts about the right solution:

- In a sense, this _is_ aa problem, or at lest an unexpeced occurrence: you call "stake", but you do not stake. So even if it is not an on-chain error (the tx goes trhough), it is still unexpected behavior that we want to communicate to the user somehow.  So perhaps (i'm not sure) it is correct to trhow an error here (a bit more informative then the current one) of the type "staking failed because the proposal is already boosted" or something like that

- we should not show the stake button in this state anyway - https://docs.google.com/document/d/1cYSX9Z6RmjSlJLPVKm6fwi4nnk2xrB0-NqXngVv61TY/edit#, so the situation should really not occur

**Comment by tibetsprague** [comment]
ok we can probable close, will be fixed by hiding buttons when staking shouldnt happen, which depends on https://github.com/daostack/client/issues/103
