### ISSUE TITLE
Default Gas Limit Too High

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#196]
Currently the gas limit that is used by the client library isn't queried from the latest block, but instead hard coded to be 6,000,000.
https://github.com/daostack/client/blob/feafe351413144d33ec552fb990f21ca7e412637/src/utils.ts#L96-L117

This price is very high, and for very simple transactions it costs around $3.

Ideally the gas limit would come from chain, but it looks like `getOptionsFromChain` isn't being used because the caller requires a synchronous routine, so `getWeb3Options` is being used instead.

I propose that this default value could be reduced by a factor of 10, giving a new value of 600,000. The only justification I have for this is that I have been doing this manually through MetaMask and transactions seem to clear just fine.

Thoughts?

**Comment by cryptogoth** [comment]
Thanks for the proposal, I think this would catch other new users off-guard when they go to submit a tx.

What about using `web3.eth.estimateGas` multiplied by about `1.1`
http://www.etherdevops.com/content/ethereum-web3ethestimategas

**Comment by jellegerbrandy** [comment]
I agree that it is better to use a realistic value rather than an arbitrary high setting, so we'll use the `estimateGas` function.

Just want to clarify that we are **not** setting the gas **price** here. The costs for the user will not change at all by changing the gas limit.

**Comment by cryptogoth** [comment]
Thanks Jelle, I agree, it's just sticker shock that might keep some people from participating. 

Sent from Yahoo Mail on Android 
 
  On Sat, May 4, 2019 at 12:07 PM, Jelle<notifications@github.com> wrote:   
I agree that it is better to use a realistic value rather than an arbitrary high setting, so we'll use the estimateGas function.

Just want to clarify that we are not setting the gas price here. The costs for the user will not change at all by changing the gas limit.

**Comment by pat-daostack** [comment]
Confirming we've had two cases of sticker shock on the BizDev side when setting up DAOs for others in the past week.

**Comment by leviadam** [comment]
I think we need to give this a bit more priority @jellegerbrandy .

It is small but very important to users.

**Comment by jellegerbrandy** [comment]
I am a bit stuck at the moment. 

A decisive vote (in this case, the vote that leads to an absolute majority) consumes more gas then the "normal" votes, and, apparently, `estimateGas` is giving too low of a value in this case. So the tests are failing with an out-of-gas error (and so would, presumably, do the transaction if it was sent with MM)...

**Comment by A-Zak** [comment]
@jellegerbrandy how much more gas does the decisive vote require? is it 20% more or 300% more?

Can we have a per call type estimation multiplier? 
So that actions that `estimateGas` is good in estimating will use that estimate, and the vote action will always multiply it by some factor...

**Comment by leviadam** [comment]
Jelle, what if we leave it empty? Is MM then working ok?

**Comment by jellegerbrandy** [comment]
Apparently yes!

**Comment by jellegerbrandy** [comment]
ok, so in the end the problem was basically traceable to the fact that I should take more breaks instead of staring at the same lines of code for an hour :-)

now the library estimates the gas limits itself (it does not rely on alchemy bec (1) in this way it can intercept the errors from the eth_estimateGas call itself and provide a better experience then MM does and (2) I do not like to rely on MM functionality as we also want to support other provider (or work as a cli)
