### ISSUE TITLE
Should All EntityClasses Inherit From IStateful<IEntityClassState>?

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#214]
Currently there are three entity classes that do not follow the pattern of inheriting from `IStateful<...>`: [Scheme](https://github.com/daostack/client/blob/27d866b8f48ea7d7dff99c25ff3f3bb34434286b/src/scheme.ts#L19), [Stake](https://github.com/daostack/client/blob/27d866b8f48ea7d7dff99c25ff3f3bb34434286b/src/stake.ts#L25), and [Vote](https://github.com/daostack/client/blob/27d866b8f48ea7d7dff99c25ff3f3bb34434286b/src/vote.ts#L25).  Should these be converted to inherit from `IStateful<...>`? If no, why not?

**Comment by jellegerbrandy** [comment]
The reason is that these objects do not change in time. So it seems overly complex for these object to have a `state()` function that returns an observable with state updates (because there never will be such updates)

So it is a tradeoff between having a consistent API and having an efficient one. It is a matter of opinion. What's yours? :-)

**Comment by dOrgJelli** [comment]
Ahh okay that makes total sense then @jellegerbrandy, I agree everything should not be treated at stateful. I'll change my usage of the library to respect both stateful & stateless entity types.
