### ISSUE TITLE
address.toLowerCase() for user provided addresses

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#338]
The client library shouldn't expect the user to provide `.toLowerCase()`d addresses, and should do this work internally. Currently in Alchemy if you try to view a DAO using a URL that has an address containing an upper-case, it fails. For example:
working - https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526 
broken - https://alchemy.daostack.io/dao/0xBe1a98d3452f6da6e0984589e545d4fc25af7526

**Comment by jellegerbrandy** [comment]
The error here is not because there is an upper case letter, but because the checksum does not compute. So the '0xBe1..` address is not a valid addres.I think this is (at least for the example of the achemy urls) the desired behavior to throw an error.

The correct checksum address works fine:

https://alchemy.daostack.io/dao/0xbe1a98d3452F6da6e0984589e545d4Fc25AF7526

**Comment by dOrgJelli** [comment]
Ah beautiful, thank you @jellegerbrandy for describing this. I hadn't read-up on checksums before so this was great to learn.
