### ISSUE TITLE
Provide a way to obtain the winning suggestions

### ISSUE THREAD

**Issue by dkent600** [daostack/client#351]
Provide a way to obtain the set of winning suggestions, and be able to identify whether a given suggestion is a winner.

**Comment by jellegerbrandy** [comment]
In the competion branch: CompeitionSuggestion has async methods:

`async getPosition()` --> will return position i winenrs list (0 -> top of the list)
`asycn isWinnerr()` --> returns true is the suggestion is winning

This will become part of the suggestion state once https://github.com/daostack/subgraph/issues/438 is resolved..

Also, `CompetitionSuggestion.search(where: {isWinner: true}, orderBy: totalVotes, orderDir: desc)` will give you the list of winners. If there is a tie, however,this list willb e wrong (pending the subgraph issue)

**Comment by jellegerbrandy** [comment]
for the list of winning suggestions, again pendingthat issue, you can do :

`competition.suggestions({orderBy: 'totalVotes', orderDirection: 'desc', first: numberOfWinners})`

this  will not be completely correct if there are ties, and when the subgraph issue is resolved, we'll be able to do 

`competition.suggestions({where: {isWinner: true}})`

**Comment by dkent600** [comment]
Heads up we may want to be able to sort by `isWinner`.  Awaiting word from Eylon about that.

**Comment by dkent600** [comment]
`isWinner` as a state property is simpler and more efficient.  I'll try with `async isWinner()`

**Comment by jellegerbrandy** [comment]
So in the 0.2.42  (which I will release as soon as the tests pass), I have let the `async isWinner` but deprecated it. The preferred way to handle this is to use the `positionInWinnerList` of the suggestion's state. 

If `positionInWinnerList === null`, the suggestion is not a winner, otherwise it is.
Pole position = `positionInWinnerList === 0`.

You can then get the list of winning suggestions by doing:

`competition.suggestions({where: {positionInWinnerList_not: null}})`

**Comment by dkent600** [comment]
`isWinner` is nice intuitive sugar.  How about leave it in and just make it return `suggestionState.positionInWinnerList === null`?

**Comment by dkent600** [comment]
I would retain `isWinner()` and move it to `ICompetitionSuggestionState` (an interface that doesn't exist, but should?)
