### ISSUE TITLE
remove superfluous query option properties

### ISSUE THREAD

**Issue by dkent600** [daostack/client#356]
I think `ICompetitionSuggestionQueryOptions.proposal` should be removed.  It should always come from Competition.id.   In any case, I note that you are always overriding it even if the caller provides it (this is a problem, see https://github.com/daostack/client/issues/357).  So again no point in having it in `ICompetitionSuggestionQueryOptions`.

Similarly, `suggestion` should be removed from `ICompetitionVoteQueryOptions` used by `CompetitionSuggestion.votes`.  The value should always come from `CompetitionSuggestion`.

**Comment by jellegerbrandy** [comment]
Well, because `Competision` is a class, it cannot come from `Competition.id`, because no such property is defined.

I agree with you that the query types are not always used completely appropriately. I.e.:

`Proposal.search(arc, {where: {dao: '0x12455})` makes sense (look for proposals with of that dao)

but:

`DAO.proposals({where: {dao: '0x1234}})` is not good - no point inbeing able to specify that.

I am using `IProposalQueryOptions` for both methods, and that interface includes the `dao` argument.

The alternative is to define different types for each of the arguments (`IProposalQueryOptions`, IDAOProposalQueryOptions`, `ISchemeProposalQueryOptions`, etc, everywhere there is a relation betweeen an entity and the set of proposals). That I did not want to do either, to not go crazy.
 

`
